{
  if (c != null) {
    try {
      c.close();
    }
 catch (    Exception e) {
      LOG.warning("Caught exception during close(): " + e);
    }
  }
}
